# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task_common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='task_common.proto',
  package='starryImage',
  syntax='proto2',
  serialized_pb=_b('\n\x11task_common.proto\x12\x0bstarryImage\"\xa2\x03\n\nTaskCommon\x12\x0e\n\x06taskId\x18\x01 \x02(\t\x12\x13\n\x0bmodelSelect\x18\x02 \x02(\t\x12\x13\n\x0b\x63reatedTime\x18\x03 \x02(\x03\x12\x16\n\x0eprocessingTime\x18\x04 \x01(\x03\x12,\n\x05image\x18\x05 \x02(\x0b\x32\x1d.starryImage.TaskCommon.Image\x12\x31\n\ntransImage\x18\x06 \x01(\x0b\x32\x1d.starryImage.TaskCommon.Image\x12.\n\x06status\x18\x07 \x02(\x0e\x32\x1e.starryImage.TaskCommon.Status\x1aG\n\x05Image\x12/\n\x04type\x18\x01 \x02(\x0e\x32!.starryImage.TaskCommon.ImageType\x12\r\n\x05image\x18\x02 \x02(\x0c\"\x1d\n\tImageType\x12\x07\n\x03JPG\x10\x01\x12\x07\n\x03PNG\x10\x02\"I\n\x06Status\x12\x07\n\x03New\x10\x01\x12\x0e\n\nProcessing\x10\x02\x12\x0f\n\x0bProcessFail\x10\x03\x12\x0b\n\x07Success\x10\x04\x12\x08\n\x04\x46\x61il\x10\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_TASKCOMMON_IMAGETYPE = _descriptor.EnumDescriptor(
  name='ImageType',
  full_name='starryImage.TaskCommon.ImageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='JPG', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PNG', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=349,
  serialized_end=378,
)
_sym_db.RegisterEnumDescriptor(_TASKCOMMON_IMAGETYPE)

_TASKCOMMON_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='starryImage.TaskCommon.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='New', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Processing', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ProcessFail', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Success', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Fail', index=4, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=380,
  serialized_end=453,
)
_sym_db.RegisterEnumDescriptor(_TASKCOMMON_STATUS)


_TASKCOMMON_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='starryImage.TaskCommon.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='starryImage.TaskCommon.Image.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image', full_name='starryImage.TaskCommon.Image.image', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=347,
)

_TASKCOMMON = _descriptor.Descriptor(
  name='TaskCommon',
  full_name='starryImage.TaskCommon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='taskId', full_name='starryImage.TaskCommon.taskId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='modelSelect', full_name='starryImage.TaskCommon.modelSelect', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='createdTime', full_name='starryImage.TaskCommon.createdTime', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='processingTime', full_name='starryImage.TaskCommon.processingTime', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image', full_name='starryImage.TaskCommon.image', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='transImage', full_name='starryImage.TaskCommon.transImage', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='starryImage.TaskCommon.status', index=6,
      number=7, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_TASKCOMMON_IMAGE, ],
  enum_types=[
    _TASKCOMMON_IMAGETYPE,
    _TASKCOMMON_STATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=453,
)

_TASKCOMMON_IMAGE.fields_by_name['type'].enum_type = _TASKCOMMON_IMAGETYPE
_TASKCOMMON_IMAGE.containing_type = _TASKCOMMON
_TASKCOMMON.fields_by_name['image'].message_type = _TASKCOMMON_IMAGE
_TASKCOMMON.fields_by_name['transImage'].message_type = _TASKCOMMON_IMAGE
_TASKCOMMON.fields_by_name['status'].enum_type = _TASKCOMMON_STATUS
_TASKCOMMON_IMAGETYPE.containing_type = _TASKCOMMON
_TASKCOMMON_STATUS.containing_type = _TASKCOMMON
DESCRIPTOR.message_types_by_name['TaskCommon'] = _TASKCOMMON

TaskCommon = _reflection.GeneratedProtocolMessageType('TaskCommon', (_message.Message,), dict(

  Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), dict(
    DESCRIPTOR = _TASKCOMMON_IMAGE,
    __module__ = 'task_common_pb2'
    # @@protoc_insertion_point(class_scope:starryImage.TaskCommon.Image)
    ))
  ,
  DESCRIPTOR = _TASKCOMMON,
  __module__ = 'task_common_pb2'
  # @@protoc_insertion_point(class_scope:starryImage.TaskCommon)
  ))
_sym_db.RegisterMessage(TaskCommon)
_sym_db.RegisterMessage(TaskCommon.Image)


# @@protoc_insertion_point(module_scope)
